In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import os
# import train
from IPython.display import display
import pickle
from main import *

In [4]:
np.set_printoptions(suppress=True, precision=6)

# Training error - Manual for NB
trainX, trainY, testX, testY = load_mnist()
print "Shapes: ", trainX.shape, trainY.shape, testX.shape, testY.shape

Shapes:  (60000L, 28L, 28L, 1L) (60000L,) (10000L, 28L, 28L, 1L) (10000L,)


In [69]:
def softmax(vec):
    evec = np.exp(vec - np.max(vec))
    s = np.sum(evec)
    return evec/s

def sigmoid(vec):
    evec = 1 + np.exp(-vec)
    return 1/evec

def test(testX):
    '''
    Complete this function.
    This function must read the weight files and
    return the predicted labels.
    The returned object must be a 1-dimensional numpy array of
    length equal to the number of examples. The i-th element
    of the array should contain the label of the i-th test
    example.
    '''
    w1 = np.loadtxt('weights/w1.csv', delimiter=',')
    w2 = np.loadtxt('weights/w2.csv', delimiter=',')
    
    sampleCount = testX.shape[0]
    
    
    x = np.ndarray((sampleCount, 28*28))
    for sample in range(sampleCount):
        x[sample, :] = np.reshape(testX[sample, :], 28*28)
    x = np.concatenate((np.ones((sampleCount, 1)), x), axis = 1)
    
    y = np.zeros(testX.shape[0])
    
    for sample in range(sampleCount):
        xi = np.ndarray((1, 785))
        xi[0,:] = np.transpose(x[sample, :])
        h = sigmoid(np.matmul(xi, w1))
        h = np.concatenate((np.ones((1, 1)), h), axis = 1)
        yi = np.matmul(h, w2).transpose()
        pi = softmax(yi)
        y[sample] = np.argmax(pi)
    return y

def train(trainX, trainY):
    '''
    Complete this function.
    '''
    print('Initializing...')

    eta_1 = 0.01
    eta_2 = eta_1
    sampleCount = trainX.shape[0]
    
    hidden_layer_size = 800
    hidden_layer = np.array([0]*hidden_layer_size)

    x = np.ndarray((sampleCount, 28*28))
    for sample in range(sampleCount):
        x[sample, :] = np.reshape(trainX[sample, :], 28*28)
    x = np.concatenate((np.ones((sampleCount, 1)), x), axis = 1)

    N1 = 28*28 + 1
    w1 = np.random.rand(N1, hidden_layer_size)/100000

    N2 = 10
    w2 = np.random.rand(hidden_layer_size + 1, N2)/100000

    epochs = 50
    for ep in range(epochs):
        batch_size = 300
        for zz in range(trainX.shape[0]/batch_size):
            sampleSet = range(zz*batch_size, min(trainX.shape[0], zz*batch_size + batch_size))
            small_x = np.ndarray((batch_size, 785))
            small_x[:,:] = x[sampleSet, :]
            
            h = sigmoid(np.dot(small_x, w1))
            h = np.concatenate((np.ones((batch_size,1)), h), axis = 1)
            
            y = np.dot(h, w2)
            
            p = np.apply_along_axis(softmax, 1, y)
            t_all = trainY[sampleSet]
            
            grad1 = p.copy()
            grad1[range(batch_size), t_all] -= 1
            
            
            delW2 = np.matmul(h.transpose(), grad1)
            temp0 = np.matmul(grad1, w2.transpose())
            temp1 = (h*(1-h))*temp0
            delW1 = np.dot(small_x.transpose(), temp1)[:, 1:]
        
            w1 = w1 - eta_1*delW1/batch_size
            w2 = w2 - eta_2*delW2/batch_size
        print 'Epoch: ', ep        
        np.savetxt('weights/w1.csv', w1, delimiter=',')
        np.savetxt('weights/w2.csv', w2, delimiter=',')

In [70]:
# print "\nDigit sample"
# print_digit(trainX[1], trainY[1])

train(trainX, trainY)

labels = test(testX)
accuracy = np.mean((labels == testY)) * 100.0
print "\nTest accuracy: %lf%%" % accuracy

Initializing...
Epoch:  0
Epoch:  1
Epoch:  2
Epoch:  3
Epoch:  4
Epoch:  5
Epoch:  6
Epoch:  7
Epoch:  8
Epoch:  9
Epoch:  10
Epoch:  11
Epoch:  12
Epoch:  13
Epoch:  14
Epoch:  15
Epoch:  16
Epoch:  17
Epoch:  18
Epoch:  19
Epoch:  20
Epoch:  21
Epoch:  22
Epoch:  23
Epoch:  24
Epoch:  25
Epoch:  26
Epoch:  27
Epoch:  28
Epoch:  29
Epoch:  30
Epoch:  31
Epoch:  32
Epoch:  33
Epoch:  34
Epoch:  35
Epoch:  36
Epoch:  37
Epoch:  38
Epoch:  39
Epoch:  40
Epoch:  41
Epoch:  42
Epoch:  43
Epoch:  44
Epoch:  45
Epoch:  46
Epoch:  47
Epoch:  48
Epoch:  49

Test accuracy: 97.110000%


In [5]:
labels = test(testX)
accuracy = np.mean((labels == testY)) * 100.0
print "\nTrain accuracy: %lf%%" % accuracy


Train accuracy: 93.570000%


In [17]:
w1 = np.loadtxt('weights/w1.csv', delimiter=',')
w2 = np.loadtxt('weights/w2.csv', delimiter=',')

display(w1)

display(w2)

array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])

array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])

array([[-0.000455, -0.000302,  0.000002, ..., -0.001047,  0.000743,
         0.000018],
       [ 0.000006,  0.000001,  0.000036, ...,  0.00008 ,  0.000074,
         0.000072],
       [ 0.000053,  0.000076,  0.000037, ...,  0.000067,  0.000075,
         0.000056],
       ..., 
       [ 0.000067,  0.000079,  0.000077, ...,  0.000079,  0.000052,
         0.000018],
       [ 0.000077,  0.00004 ,  0.000085, ...,  0.000062,  0.000008,
         0.000021],
       [ 0.000058,  0.000062,  0.000097, ...,  0.000077,  0.000045,
         0.000031]])