In [2]:
import numpy as np

In [7]:
A = np.random.rand(3,5)
B = np.ones((5, 2))

print A
print np.dot(A,B)

[[ 0.55816567  0.15534383  0.25409463  0.84228315  0.27134083]
 [ 0.29794503  0.80297564  0.33712733  0.01701469  0.10711934]
 [ 0.44741376  0.8560588   0.28153865  0.64863188  0.65742424]]
[[ 2.08122811  2.08122811]
 [ 1.56218202  1.56218202]
 [ 2.89106733  2.89106733]]
